---
title: "Practice Activity 9.2"
format: html
editor: visual
---

# Warm-up

```{r}
library(tidyverse)

#95th percentile for trumpet weight
qunif(p = .95, min = 1.5, max = 3.5)

# 10th percentile 
qnorm(p = .10, mean = 4.6, sd = 0.8)

# what percent trombones over 5 pounds?
pnorm(q = 5, mean = 4.6, sd = 0.8, lower.tail = FALSE)

# reed over 5 
pchisq(q = 5, df = 4, lower.tail = FALSE)

# 100 RANDOM TROMBONE WEIGHTS, BELOW 4 LBS
trombone_weights <- rnorm(n = 100, mean = 4.6, sd = 0.8)

trombone_weights[trombone_weights < 4]

```

# Catching a Con

```{r}
set.seed(1957)

music_man <- function(n_tromb, n_cor, n_reed) {
  
  trombones <- rnorm(n_tromb, mean = 4.6, sd = 0.8)
  cornets <- runif(n_cor, min = 1.5, max = 3.5)
  reeds <- rchisq(n_reed, df = 4)

  return(sum(trombones, cornets, reeds))

}

reed_total <- 542 + 318 + 175
total_weight <- 4532

my_weights <- map_dbl(.x = 1:1000, 
                      .f = ~ music_man(n_tromb = 76, 
                                       n_cor = 110, 
                                       n_reed = reed_total)
                      ) 

length(my_weights[my_weights < total_weight])
```
